### ISSUE TITLE
Broken link in "REPORT AN ISSUE ON THIS PAGE"

### ISSUE THREAD

**Issue by tzach** [scylladb/care-pet#11]
![image](https://user-images.githubusercontent.com/170200/93053918-32120300-f671-11ea-9bcb-0e863546bc1f.png)
Should be `https://github.com/scylladb/care-pet/...` not `https://github.com/scylladb/scylla-monitoring/...`

**Comment by tzach** [comment]
@lauranovich

**Comment by lauranovich** [comment]
on it

**Comment by lauranovich** [comment]
@sitano -we can close ?

**Comment by sitano** [comment]
@larisau yep! thx!
