### ISSUE TITLE
How do I check the generated documentation?

### ISSUE THREAD

**Issue by DanielHe4rt** [scylladb/care-pet#120]
Hey! How you guys doing? 

I'm trying to make an implementation of PHP Cassandra/Scylla driver but there's a message when I push a commit saying that has some kind of documentation but I can access it to verify if it's everything ok.

PR: #119 
![image](https://user-images.githubusercontent.com/6912596/211177833-54aa1310-620d-4b7f-8d9a-098609ec36e3.png)

There's any possibility to see the live documentation before merge it? 

Cheers,
danielhe4rt

**Comment by tzach** [comment]
Yes, from your terminal:
```
cd docs
make preview
```

**Comment by DanielHe4rt** [comment]
Cool, worked here.
