### ISSUE TITLE
Care Pet Guide Error: IO Error: No connections in the pool

### ISSUE THREAD

**Issue by a-creation** [scylladb/care-pet#123]
After starting three nodes using `docker-compose up -d` and ensuring the three nodes are in UN (up-normal) status, I run `NODE1=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' carepet-scylla1)
cargo run --bin migrate -- --hosts $NODE1` as stated in the guide. This results in Error: IO Error: No connections in the pool. This is all in the Rust directory of the repo.

I'm on a M1 Mac.

![Screen Shot 2023-01-24 at 1 24 00 PM](https://user-images.githubusercontent.com/60591313/214376432-9c8421a2-3ef0-47e8-9421-b6b6894d6b02.png)

**Comment by tzach** [comment]
Just validate the example on Fedroa and it works, so it might be M1 related.

**Comment by tzach** [comment]
Can you run
```
docker logs carepet-scylla1
```
and share any error?

**Comment by Nsandomeno** [comment]
I'm on intel mac and experiencing the same thing. I receive the boot-up logs when running that command above, but from clearing and attempting to run `bin/migrate/main.rs` over again, I see no new logs are generated from the attempt. This is probably a connectivity issue between localhost and the Docker network being used.

**Comment by Nsandomeno** [comment]
Read this conversation:[ ](https://groups.google.com/g/scylladb-users/c/rjz061ECJb8?pli=1)
