### ISSUE TITLE
docs: Issue in page Build an IoT App with Python

### ISSUE THREAD

**Issue by guy9** [scylladb/care-pet#128]
I would like to report an issue in page https://iot.scylladb.com/master/build-with-python

### Problem
Under the IOT docs, some languages, for example PHP, direct the use to clone the repo and handle dependencies (covered in the getting started section), while others, like GO, refer the use to the getting started section. 
###  Suggest a fix
It should be consistent, so either all languages refer to the getting started section, or none do. 
My personal preference is that they do, so there is not duplication in each part, the downside for this option is that each section is not standalone.

**Comment by DanielHe4rt** [comment]
Fixed and merged #152
