### ISSUE TITLE
docs: Issue in page Getting Started with CarePet: A sample IoT App

### ISSUE THREAD

**Issue by guy9** [scylladb/care-pet#131]
I would like to report an issue in page https://iot.scylladb.com/master/getting-started

### Problem
The instructions on this page create a go application, while the title of the page (and the subpages) indicate it will be a generic getting started page. 

###  Suggest a fix
This page should be generic. Application-specific instructions should be on the next pages. 
Another option is to say this is generic but show an example with go

**Comment by DanielHe4rt** [comment]
Fixed and merged!
