### ISSUE TITLE
docs: Issue in page Getting Started with CarePet: A sample IoT App

### ISSUE THREAD

**Issue by guy9** [scylladb/care-pet#132]
I would like to report an issue in page https://iot.scylladb.com/master/getting-started

### Problem
Running the instructions on this page results in an error in the go-app:
[guy@fedora go]$ docker logs 1e118e735025
Cloning into '/care-pet'...
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/scylladb/gocqlx/v2 v2.1.0
go: downloading github.com/scylladb/gocql v1.4.0
go: downloading github.com/scylladb/go-reflectx v1.0.1
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
go: downloading github.com/go-openapi/loads v0.19.5
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/go-openapi/strfmt v0.19.5
go: downloading github.com/go-openapi/runtime v0.19.20
go: downloading github.com/go-openapi/validate v0.19.10
go: downloading github.com/go-openapi/errors v0.19.6
go: downloading github.com/mitchellh/mapstructure v1.3.2
go: downloading github.com/go-openapi/swag v0.19.9
go: downloading go.mongodb.org/mongo-driver v1.3.4
go: downloading github.com/asaskevich/govalidator v0.0.0-20200428143746-21a406dcc535
go: downloading github.com/go-openapi/analysis v0.19.10
go: downloading github.com/mailru/easyjson v0.7.1
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/go-openapi/spec v0.19.9
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: downloading github.com/go-stack/stack v1.8.0
go: downloading github.com/go-openapi/jsonreference v0.19.4
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading golang.org/x/text v0.3.3
tail: cannot open 'anything' for reading: No such file or directory
[guy@fedora go]$ 

###  Suggest a fix

**Comment by DanielHe4rt** [comment]
Go example fixed and merged!
