### ISSUE TITLE
docs: Issue in page Build an IoT App with Rust

### ISSUE THREAD

**Issue by chetan2309** [scylladb/care-pet#140]
I would like to report an issue in page https://iot.scylladb.com/master/build-with-rust

### Problem

After setting up Cluster with 3 nodes locally using docker compose. I ran the migration script

**cargo run --bin migrate -- --hosts $NODE1**

I keep getting this error: below-
Error: IO Error: No connections in the pool
error: process didn't exit successfully: `target\debug\migrate.exe --hosts 172.20.0.2` (exit code: 1)

Then I end up stumbling upon this issue - https://github.com/scylladb/scylla-rust-driver/issues/335

Where Jasperav suggested running this one node resolves this. 

**"Hmm after investigating a bit, it turned out that running multiple nodes (in Docker) is the problem, not the amount of sessions created. Running a single node works. "**

Since I am running this for learning purposes. I modified the docker file and removed two additional nodes and ran this migration script with one node. I am still getting same error.

**Error: IO Error: No connections in the pool
error: process didn't exit successfully: `target\debug\migrate.exe --hosts 172.20.0.2` (exit code: 1)**

###  Suggest a fix

Don't have a fix yet. But what I did notice is that a lot of rust packages are severely outdated. If I try switching to latest Scylla rust driver, then code doesn't even compile.

Thanks,
Chetan

**Comment by DanielHe4rt** [comment]
Fixed and merged!
