### ISSUE TITLE
Provide code snippets to cover standard usage patterns

### ISSUE THREAD

**Issue by sitano** [scylladb/care-pet#15]
1. Provide code snippets to cover standard usage patterns
2. Multi-platform

Expected snippets to have:
1. how to initialize new project with drivers
2. how to connect to db
3. how to define a data model
4. how to execute a query
5. how to work with a data model
6. how to read from db
7. how to create schema
8. how to write cassandra-stress profile for your app and execute it

What we have:
- how to start docker-compose scylla cluster
- how to exec cqlsh and nodetool on docker cluster
- how to build and execute database schema migration tool
- how to describe keyspace and tables with cqlsh
- how to build sensor app and execute it
- how to build rest service and execute it
- how to work with rest service

Go-specific:
- How to start a new project (1)
- How to connect to the database and get a session (2)
- How to execute a query (4)
- How to use ORM (save a model) (5)

Thus Go part is missing: 3, 6, 7

Java-specific:
- How to start a new project (1)
- How to connect to the database and get a session (2)
- How to define a data model (3) (mapper, dao, deps) [need some more details]
- How to execute a query (4)
- How to gather all the dependencies to run the app

Thus Go part is missing: 5, 6, 7

TODO:
- research what coding best practices to present for the IoT-specifics. Ideas: data buffering, delta-encoding, compression.

**Comment by sitano** [comment]
An example of tabs doc syntax:

```
.. tabs::

   .. group-tab:: CentOS 7, Ubuntu 16.04/18.04, Debian 8/9

      .. code-block:: shell

         sudo systemctl stop scylla-server

   .. group-tab:: Ubuntu 14.04, Debian 7

      .. code-block:: shell

         sudo service scylla-server stop

   .. group-tab:: Docker

      .. code-block:: shell

         docker exec -it some-scylla supervisorctl stop scylla

      (without stopping *some-scylla* container)

This is the syntax
Note how each tab is indented spacing is "space sensitive"

the code-block directive can be any language and will use syntax highlighting by default. 
```

**Comment by lauranovich** [comment]
Related to https://github.com/scylladb/care-pet/issues/10 and https://github.com/scylladb/care-pet/issues/26

**Comment by tzach** [comment]
Closing. Most point are done.
