### ISSUE TITLE
Embedding iFrame at index.rst

### ISSUE THREAD

**Issue by DanielHe4rt** [scylladb/care-pet#153]
Hey @dgarcia360! I'm trying to embed an `iframe` in the index.rst page but with no luck. 

Should I enable a feature to make it work? 

This is the Embed in the case (you can use it for now, the token will be replaced):

<iframe width="1140"
  height="640"
  sandbox="allow-forms allow-modals allow-popups allow-same-origin allow-scripts"
  src="https://play.instruqt.com/embed/scylladb/tracks/carepet-rust?token=em_Z_xvk5h6RxovmnDS&show_challenges=true" style="border: 0;"
  allowfullscreen>
</iframe>

**Comment by dgarcia360** [comment]
To include an iframe on any RST page, you should use the following directive:


```
.. raw:: html

    <iframe width="1140" height="640" sandbox="allow-forms allow-modals allow-popups allow-same-origin allow-scripts" src="https://play.instruqt.com/embed/scylladb/tracks/carepet-rust?token=em_Z_xvk5h6RxovmnDS&show_challenges=true" style="border: 0;" allowfullscreen></iframe>
```

**Comment by DanielHe4rt** [comment]
Seems to work properly now, thanks! The problem was the indentation/spacing of the html blocks. 

I'll merge a PR in the next minutes with the changes.
