### ISSUE TITLE
Add code snippet for each implementation: Go, Java...

### ISSUE THREAD

**Issue by tzach** [scylladb/care-pet#26]
We should use tabs to switch between the examples

**Comment by lauranovich** [comment]
We need to get the samples first. 
once we have them adding the tabs is easy

**Comment by lauranovich** [comment]
Related to https://github.com/scylladb/care-pet/issues/15

**Comment by lauranovich** [comment]
related to https://github.com/scylladb/care-pet/issues/10

**Comment by tzach** [comment]
Completed!
