### ISSUE TITLE
Docs: Learn how to contribute lead to non relevant link

### ISSUE THREAD

**Issue by tzach** [scylladb/care-pet#38]
Link to https://docs.scylladb.com/contribute/ is not relevant to this project
We should make it conferrable, and remove it by default and in this project

**Comment by lauranovich** [comment]
Contribute button on the inner pages 
Has a "how to contribute"
this links to Scylla's repo. 

Each project needs to have its own content. This needs to be configured in each project's conf.py file

**Comment by lauranovich** [comment]
Suggestion:
We move this issue to the theme
Suggestion number 2 
we add the following
How to Contribute to Docs  ---> links to https://sphinx-theme.scylladb.com/stable/contribute/
How to Contribute to Code --> links to the gitHub repo ( but a md page needs to be created explaining what to do to contribute) - if all projects have a contribute.md file, then we can make a generic link which will always work.
