### ISSUE TITLE
Issue in page Getting Started with CarePet: A sample IoT App

### ISSUE THREAD

**Issue by guy9** [scylladb/care-pet#44]
I would like to report an issue in page https://care-pet.docs.scylladb.com/master/getting_started

### Problem
The entire page seems out of date and needs review. Some examples:
1. It talks about a three node cluster while the docker-compose file starts a one node cluster
2. The name of the node in docker-compose is carepet-scylla while this page references "carepet-scylla1"
3. After the git clone step need to "cd quick-start" before running docker-compose
4. Need to remove "$" sign from the commands to copy otherwise they can not be copy pasted
5. etc.

###  Suggest a fix

**Comment by tzach** [comment]
@raoufchebri FYI
